### ISSUE TITLE
Scripts fail with Python 3.7 and gpiozero 1.5.1

### ISSUE THREAD

**Issue by dpisanu** [modmypi/Programmable-Christmas-Star#1]
Hi,

I was just giving the [christmas star](https://thepihut.com/products/raspberry-pi-christmas-tree-star) a spin and am running into several issues.

Only all_on.py works but throws alot of errors.
The other scripts _in_out.py_, _random_leds.py_, _slow_walk.py_,  _starcommander.py_ and _twinkle.py_ exit out fast and have no effect on the LEDs.

I have Python 3.7 installed.
The gpiozero package installed via pip3.
> pip3 show gpiozero
> Name: gpiozero
> Version: 1.5.1
> Summary: A simple interface to GPIO devices with Raspberry Pi.
> Home-page: https://github.com/RPi-Distro/python-gpiozero
> Author: Ben Nuttall
> Author-email: ben@raspberrypi.org
> License: BSD License
> Location: /usr/local/lib/python3.7/dist-packages
> Requires: colorzero

Taking **twinkle.py** for example.
> python3 twinkle.py
> /usr/local/lib/python3.7/dist-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpigpio: No module named 'RPi'
  'Falling back from %s: %s' % (name, str(e))))
> /usr/local/lib/python3.7/dist-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from rpio: No module named 'RPIO'
  'Falling back from %s: %s' % (name, str(e))))
> /usr/local/lib/python3.7/dist-packages/gpiozero/devices.py:279: PinFactoryFallback: Falling back from pigpio: No module named 'pigpio'
  'Falling back from %s: %s' % (name, str(e))))
> Traceback (most recent call last):
>   File "twinkle.py", line 4, in <module>
>     star = Star(pwm=True)
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/devices.py", line 124, in __call__ self = super(GPIOMeta, cls).__call__(*args, **kwargs)
>   File "/home/pi/Programmable-Christmas-Star/star.py", line 16, in __init__ pin_factory=pin_factory),
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/devices.py", line 124, in __call__self = super(GPIOMeta, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/boards.py", line 415, in __init__ super(LEDBoard, self).__init__(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/boards.py", line 335, in __init__
    for name, pin_or_collection in kwargs.items()
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/boards.py", line 335, in <dictcomp> for name, pin_or_collection in kwargs.items()
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/devices.py", line 124, in __call__ self = super(GPIOMeta, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/output_devices.py", line 418, in __init__ self.pin.frequency = frequency
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/__init__.py", line 358, in <lambda> lambda self, value: self._set_frequency(value),
>   File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/__init__.py", line 354, in _set_frequency raise PinPWMUnsupported("PWM is not supported on pin %r" % self)
gpiozero.exc.PinPWMUnsupported: PWM is not supported on pin GPIO8

Is there some compatibility issue with the scripts and later versions of python3 + the gpiozero package?

**Comment by dpisanu** [comment]
**facepalm** was missing the pip3 install of **RPi.GPIO**
Maybe should be added to the _Readme.md_ in case somebody else runs into this.
